apiVersion: v1
kind: Service
metadata:
  name: api-node-service
  labels:
    name: api-node-service
  annotations:
    dev.marciopaulo.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    name: apinode